language: cpp
os: windows
env:
  - CMAKE_PATH="/c/Program Files/CMake/bin"
script: 
  - choco install pkgconfiglite
  - git clone https://github.com/Microsoft/vcpkg ../vcpkg -v
  - /vcpkg/bootstrap-vcpkg.bat
  - vcpkg install ZLIB
  - vcpkg install harfbuzz
  - vcpkg install PNG 
  - vcpkg install BZip2 
  #- choco install ninja
  - export PATH=$CMAKE_PATH:$PATH
  - mkdir build && cd build
  - cmake .. 
  - dir
  #- cmake -DCMAKE_BUILD_TYPE=Debug . 
  #- cmake -DCMAKE_BUILD_TYPE=Release . 
