language: cpp
os: windows
env:
  - CMAKE_PATH="/c/Program Files/CMake/bin"
script: 
  #- choco install pkgconfiglite
  #- git clone https://github.com/Microsoft/vcpkg ../vcpkg -v
  #- ../vcpkg/bootstrap-vcpkg.bat
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install ZLIB
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe installl harfbuzz
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install PNG 
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install BZip2 
  #- choco install ninja
  - export PATH=$CMAKE_PATH:$PATH
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --target FreeType --config Release 
  #- dir
  #- cmake -DCMAKE_BUILD_TYPE=Debug . 
  #- cmake -DCMAKE_BUILD_TYPE=Release . 
deploy:
  provider: pages
  #script:	grunt gh-pages
  skip_cleanup: true
  github_token: $GH_TOKEN 
  keep_history: false
  on:
    tags: false
    repo: HarrievG/FreeType
    
    