language: cpp
os: windows
env:
  - CMAKE_PATH="/c/Program Files/CMake/bin"
script: 
  #- choco install pkgconfiglite
  #- git clone https://github.com/Microsoft/vcpkg ../vcpkg -v
  #- ../vcpkg/bootstrap-vcpkg.bat
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install ZLIB
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe installl harfbuzz
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install PNG 
  #- ../toolsrc/msbuild.x86.release/vcpkg.exe install BZip2 
  #- choco install ninja
  - export PATH=$CMAKE_PATH:$PATH
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --target FreeType --config Release 
  deploy:
	provider: pages
	skip_cleanup: true
	github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
	keep_history: true
	on:
		branch: master
  #- dir
  #- cmake -DCMAKE_BUILD_TYPE=Debug . 
  #- cmake -DCMAKE_BUILD_TYPE=Release . 
