# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
#- script: mkdir build && cd build
#  displayName: 'Creating and entering Build Directory'
- script: cmake ..
  displayName: 'Running cmake to generate build conifg'
- script: cmake --build . --target FreeType --config Release
  displayName: 'Building FreeType Release'

  
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
